title: Uriel
author: Judka Linkov
email: judka@uriel.world
logo: /logo.jpg
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "https://uriel.world" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  judka-uriel
repository: https://github.com/judka-uriel/judka-uriel.github.io

permalink: /:title # without :output_ext .html

defaults:
  - scope:
      path: "" # an empty string here means all files in the project
    values:
      lang: en
      styles:
        - /files/tailwind.css
# - scope:
#     path: en/book
#   values:
#     lang: en
#     layout: book
# - scope:
#     path: en/judka
#   values:
#     lang: en
#     layout: card
#     nav: "nav_en"
#     nav_title: "Site Map"
  - scope:
      path: ru/book
    values:
      lang: ru
      layout: book
      styles:
        - /files/book/page.css
        - /files/book/book.css
  - scope:
      path: ru/judka
    values:
      lang: ru
      layout: card
      nav: "nav_ru"
      nav_title: "Карта сайта"

plugins:
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# sass:
#   style: compressed
