title: Uriel
author: Judka Linkov
email: judka@uriel.world
logo: /logo.jpg
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "https://uriel.world" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  judka-uriel
repository: https://github.com/judka-uriel/judka-uriel.github.io

permalink: /:title # without :output_ext .html

defaults:
  - scope:
      path: "" # an empty string here means all files in the project
    values:
      lang: en
      layout: card
      styles:
        - /files/tailwind.css
      nav: "nav_en"
      nav_title: "Sitemap"
  - scope:
      path: ru
    values:
      lang: ru
      nav: "nav_ru"
      nav_title: "Карта сайта"
  - scope:
      path: en/book
    values:
      layout: book
      styles:
        - /files/book/page.css
        - /files/book/book.css
  - scope:
      path: ru/book
    values:
      layout: book
      styles:
        - /files/book/page.css
        - /files/book/book.css

plugins:
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# sass:
#   style: compressed
